from __future__ import annotations

import logging

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.api.routes_auth import router as auth_router
from app.api.routes_chat import router as chat_router
from app.api.routes_documents import router as documents_router
from app.api.routes_system import router as system_router
from app.core.config import settings
from app.services.user_service import ensure_default_user

logger = logging.getLogger("rag")

DESCRIPTION = """
RAG document assistant API.

Upload PDFs, then ask questions in natural language. Answers are generated by an
LLM using only the retrieved chunks, and every answer returns its source pages.
"""


def create_app() -> FastAPI:
    app = FastAPI(
        title=settings.app_name,
        description=DESCRIPTION,
        version="1.0.0",
        docs_url="/docs",
        openapi_url="/openapi.json",
    )

    origins = settings.cors_origin_list
    app.add_middleware(
        CORSMiddleware,
        allow_origins=origins,
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    for router in (system_router, auth_router, documents_router, chat_router):
        app.include_router(router, prefix=settings.api_prefix)

    @app.get("/", tags=["system"])
    def root() -> dict[str, str]:
        return {
            "name": settings.app_name,
            "docs": "/docs",
            "health": f"{settings.api_prefix}/health",
        }

    settings.ensure_directories()
    seeded = ensure_default_user()
    if seeded is not None:
        logger.info("Seeded default user %s", seeded.email)
    if not origins:
        logger.warning(
            "CORS_ORIGINS resolved to an empty list, so every cross-origin "
            "request will be rejected. Set CORS_ORIGINS to the frontend origin."
        )
    logger.info(
        "Started with ollama=%s model=%s cors_origins=%s",
        settings.ollama_base_url,
        settings.llm_model,
        origins or "<none>",
    )
    return app


app = create_app()
